### ISSUE TITLE
Could not load file or assembly 'NuGet.ProjectModel, Version=4.6.0.1, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.

### ISSUE THREAD

**Issue by v-atian** [v-atian/NuGetClientTests#12]
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at Apex.NuGetClient.ObjectModel.TestServices.NuGetApexUITestService.GetProjectPackageManagerControl(String projectUniqueName) in C:\NuGet.Client.Test\NuGetClientTests\Apex.NuGetClient\ObjectModel\TestServices\NuGetApexUITestService.cs:line 26
   at Apex.NuGetClient.ObjectModel.TestServices.NuGetApexUITestService.GetApexTestUIProject(String project) in C:\NuGet.Client.Test\NuGetClientTests\Apex.NuGetClient\ObjectModel\TestServices\NuGetApexUITestService.cs:line 21
   at Apex.NuGetClient.TestServices.NuGetApexTestService.GetUIWindowfromProject(ProjectTestExtension project) in C:\NuGet.Client.Test\NuGetClientTests\Apex.NuGetClient\TestServices\NuGetApexTestService.cs:line 40
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Apex.NuGetClient.TestServices.NuGetApexTestService.GetUIWindowfromProject(ProjectTestExtension project)
   at NuGet.Client.Tests.Tests.E2E.AbuseLinkTests.AbuseLink() in C:\NuGet.Client.Test\NuGetClientTests\NuGet.Client.Tests\Tests\E2E\AbuseLinkTests.cs:line 30

**Comment by v-atian** [comment]
Server stack trace: 
   at Apex.NuGetClient.ObjectModel.TestServices.NuGetApexUITestService.<>c__DisplayClass2_0.<<GetProjectPackageManagerControl>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Apex.NuGetClient.ObjectModel.TestServices.NuGetApexUITestService.<>c__DisplayClass2_0.<GetProjectPackageManagerControl>b__0()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.ExecuteJob[T](Func`1 asyncMethod, JoinableTask job)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at Apex.NuGetClient.ObjectModel.TestServices.NuGetApexUITestService.GetProjectPackageManagerControl(String projectUniqueName) in C:\NuGet.Client.Test\NuGetClientTests\Apex.NuGetClient\ObjectModel\TestServices\NuGetApexUITestService.cs:line 26
   at Apex.NuGetClient.ObjectModel.TestServices.NuGetApexUITestService.GetApexTestUIProject(String project) in C:\NuGet.Client.Test\NuGetClientTests\Apex.NuGetClient\ObjectModel\TestServices\NuGetApexUITestService.cs:line 21
   at Apex.NuGetClient.TestServices.NuGetApexTestService.GetUIWindowfromProject(ProjectTestExtension project) in C:\NuGet.Client.Test\NuGetClientTests\Apex.NuGetClient\TestServices\NuGetApexTestService.cs:line 40
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

**Comment by v-atian** [comment]
Test Name:	AbuseLink - Wpf.v_4_5_2.VS
Test FullName:	NuGet.Client.Tests.Tests.E2E.AbuseLinkTests.AbuseLink
Test Source:	C:\NuGet.Client.Test\NuGetClientTests\NuGet.Client.Tests\Tests\E2E\AbuseLinkTests.cs : line 22
Test Outcome:	Failed
Test Duration:	0:00:25.075

Result StackTrace:	
Server stack trace: 
   at Apex.NuGetClient.ObjectModel.TestServices.NuGetApexUITestService.<>c__DisplayClass2_0.<<GetProjectPackageManagerControl>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Apex.NuGetClient.ObjectModel.TestServices.NuGetApexUITestService.<>c__DisplayClass2_0.<GetProjectPackageManagerControl>b__0()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.ExecuteJob[T](Func`1 asyncMethod, JoinableTask job)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at Apex.NuGetClient.ObjectModel.TestServices.NuGetApexUITestService.GetProjectPackageManagerControl(String projectUniqueName) in C:\NuGet.Client.Test\NuGetClientTests\Apex.NuGetClient\ObjectModel\TestServices\NuGetApexUITestService.cs:line 26
   at Apex.NuGetClient.ObjectModel.TestServices.NuGetApexUITestService.GetApexTestUIProject(String project) in C:\NuGet.Client.Test\NuGetClientTests\Apex.NuGetClient\ObjectModel\TestServices\NuGetApexUITestService.cs:line 21
   at Apex.NuGetClient.TestServices.NuGetApexTestService.GetUIWindowfromProject(ProjectTestExtension project) in C:\NuGet.Client.Test\NuGetClientTests\Apex.NuGetClient\TestServices\NuGetApexTestService.cs:line 40
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Apex.NuGetClient.TestServices.NuGetApexTestService.GetUIWindowfromProject(ProjectTestExtension project)
   at NuGet.Client.Tests.Tests.E2E.AbuseLinkTests.AbuseLink() in C:\NuGet.Client.Test\NuGetClientTests\NuGet.Client.Tests\Tests\E2E\AbuseLinkTests.cs:line 30
Result Message:	System.IO.FileNotFoundException : Could not load file or assembly 'NuGet.ProjectModel, Version=4.6.0.1, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.

**Comment by v-atian** [comment]
Mismatch reference "NuGet.ProjectModel" https://github.com/v-atian/NuGetClientTests/commit/03c9e64a3af232b9ff1fc34a97d683938e93cce3
