### ISSUE TITLE
System.ArgumentNullException: 'Value cannot be null.

### ISSUE THREAD

**Issue by v-atian** [v-atian/NuGetClientTests#21]
Value cannot be null.
Parameter name: uriString

Server stack trace: 
   at System.Uri..ctor(String uriString)
   at Microsoft.Test.Apex.VisualStudio.Solution.SolutionService.CreateEmptySolution(String solutionName, String path)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.Test.Apex.VisualStudio.Solution.SolutionService.CreateEmptySolution(String solutionName, String path)
   at NuGetClient.Test.Integration.Platform.PlatformContextDetailsBase.CreateAspNetWebSolution(VisualStudioHost host, String solutionDirectory, String projectName, AspNetWebTemplateData templateData) in C:\NuGetClientTests\NuGet.Client.Tests\Platform\PlatformContextDetailsBase.cs:line 84
   at NuGetClient.Test.Integration.Platform.AspNetEmptyPlatformContextDetails.CreateAspNetWebSolution(VisualStudioHost host, String solutionDirectory, String projectName, AspNetWebTemplateData templateData) in C:\NuGetClientTests\NuGet.Client.Tests\Platform\AspNetEmptyPlatformContextDetails.cs:line 36
   at NuGetClient.Test.Integration.Platform.ContextImplementation.CreateAspNetWebSolution(VisualStudioHost host, AspNetWebTemplateData template) in C:\NuGetClientTests\NuGet.Client.Tests\Platform\ContextImplementation.cs:line 83
   at NuGetClient.Test.Integration.Tests.E2E.AbuseLinkTests.AbuseLink() in C:\NuGetClientTests\NuGet.Client.Tests\Tests\E2E\AbuseLinkTests.cs:line 29

**Comment by v-atian** [comment]
https://github.com/v-atian/NuGetClientTests/commit/f12e336c4d6ab6ba2480f531a6806812ba5916aa
