### ISSUE TITLE
System.IO.PathTooLongException : The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.

### ISSUE THREAD

**Issue by v-atian** [v-atian/NuGetClientTests#22]
Test Name:	AbuseLink - AspNetEmptyWebApplication.v_4_6_2.VS
Test FullName:	NuGetClient.Test.Integration.Tests.E2E.AbuseLinkTests.AbuseLink
Test Source:	C:\NuGetClientTests\NuGet.Client.Tests\Tests\E2E\AbuseLinkTests.cs : line 22
Test Outcome:	Failed
Test Duration:	0:06:27.035

Result StackTrace:	
at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at NuGet.ProjectManagement.FolderNuGetProject.GetInstalledPackageFilePath(PackageIdentity packageIdentity)
   at NuGet.PackageManagement.PackagePreFetcher.<GetPackagesAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__75.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__75.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<InstallPackageAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<InstallPackageAsync>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.VisualStudio.VsPackageInstaller.<InstallInternalCoreAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.VisualStudio.VsPackageInstaller.<InstallInternalAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at NuGet.VisualStudio.VsPackageInstaller.<InstallInternalAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.VisualStudio.VsPackageInstaller.<>c__DisplayClass23_0.<<InstallPackagesFromRegistryRepository>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at NuGet.VisualStudio.VsPackageInstaller.RunJTFWithCorrectContext(Project project, Func`1 asyncTask)
   at NuGet.VisualStudio.VsPackageInstaller.InstallPackagesFromRegistryRepository(String keyName, Boolean isPreUnzipped, Boolean skipAssemblyReferences, Boolean ignoreDependencies, Project project, IDictionary`2 packageVersions)
   at NuGet.VisualStudio.VsPackageInstaller.InstallPackagesFromRegistryRepository(String keyName, Boolean isPreUnzipped, Boolean skipAssemblyReferences, Project project, IDictionary`2 packageVersions)
   at Microsoft.VisualStudio.Web.Project.AddNugetPackagesRule.Execute(Project project, String projectPath, IOneASPNETModel wizardModel, RuleOption selectedOption, Boolean collectionPhase)
   at Microsoft.VisualStudio.Web.Project.ReferencedRule.Execute(Project project, String projectPath, IOneASPNETModel wizardModel, RuleOption selectedOption, Boolean collectionPhase)
   at Microsoft.VisualStudio.Web.Project.ApplyRulesRule.Execute(Project project, String projectPath, IOneASPNETModel wizardModel, RuleOption selectedOption, Boolean collectionPhase)
   at Microsoft.VisualStudio.Web.Project.ApplyRulesRule.Execute(Project project, String projectPath, IOneASPNETModel wizardModel, RuleOption selectedOption, Boolean collectionPhase)
   at Microsoft.VisualStudio.Web.Project.OneASPNETModel.ApplyRules(Project project, String projectPath, RuleOption selectedOption, Boolean collectionPhase)
   at Microsoft.VisualStudio.Web.Project.OneASPNETModel.CreateProject(Solution solution)
   at Microsoft.VisualStudio.Web.Project.OneASPNetProjectTemplateWizard.Microsoft.VisualStudio.TemplateWizard.IWizard.RunFinished()
   at Microsoft.VisualStudio.TemplateWizard.Wizard.Execute(Object application, Int32 hwndOwner, Object[]& ContextParams, Object[]& CustomParams, wizardResult& retval)
   at EnvDTE.SolutionClass.AddFromTemplate(String FileName, String Destination, String ProjectName, Boolean Exclusive)
   at NuGetClient.Test.Integration.Platform.PlatformContextDetailsBase.CreateAspNetWebSolution(VisualStudioHost host, String solutionDirectory, String projectName, AspNetWebTemplateData templateData) in C:\NuGetClientTests\NuGet.Client.Tests\Platform\PlatformContextDetailsBase.cs:line 96
   at NuGetClient.Test.Integration.Platform.AspNetEmptyPlatformContextDetails.CreateAspNetWebSolution(VisualStudioHost host, String solutionDirectory, String projectName, AspNetWebTemplateData templateData) in C:\NuGetClientTests\NuGet.Client.Tests\Platform\AspNetEmptyPlatformContextDetails.cs:line 36
   at NuGetClient.Test.Integration.Platform.ContextImplementation.CreateAspNetWebSolution(VisualStudioHost host, AspNetWebTemplateData template) in C:\NuGetClientTests\NuGet.Client.Tests\Platform\ContextImplementation.cs:line 83
   at NuGetClient.Test.Integration.Tests.E2E.AbuseLinkTests.AbuseLink() in C:\NuGetClientTests\NuGet.Client.Tests\Tests\E2E\AbuseLinkTests.cs:line 29
Result Message:	System.IO.PathTooLongException : The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.

**Comment by v-atian** [comment]
https://github.com/v-atian/NuGetClientTests/commit/431a1837c7a32708e23e3d7f4a54310b34c89d4b
