### ISSUE TITLE
System.Runtime.InteropServices.COMException : Cannot create project. The project folder 'C:\school\ApexSolutions\WebApplication\' already exists and contains other files and folders

### ISSUE THREAD

**Issue by v-atian** [v-atian/NuGetClientTests#24]
Test Name:	AbuseLink - AspNetEmptyWebApplication.v_4_6_2.VS
Test FullName:	NuGetClient.Test.Integration.Tests.E2E.AbuseLinkTests.AbuseLink
Test Source:	C:\NuGetClientTests\NuGet.Client.Tests\Tests\E2E\AbuseLinkTests.cs : line 23
Test Outcome:	Failed
Test Duration:	0:00:37.187

Result StackTrace:	
at EnvDTE.SolutionClass.AddFromTemplate(String FileName, String Destination, String ProjectName, Boolean Exclusive)
   at Microsoft.VisualStudio.TemplateWizard.Wizard.Execute(Object application, Int32 hwndOwner, Object[]& ContextParams, Object[]& CustomParams, wizardResult& retval)
   at EnvDTE.SolutionClass.AddFromTemplate(String FileName, String Destination, String ProjectName, Boolean Exclusive)
   at Microsoft.VisualStudio.Web.Project.OneASPNETModel.CreateProject(Solution solution)
   at Microsoft.VisualStudio.Web.Project.OneASPNetProjectTemplateWizard.Microsoft.VisualStudio.TemplateWizard.IWizard.RunFinished()
   at Microsoft.VisualStudio.TemplateWizard.Wizard.Execute(Object application, Int32 hwndOwner, Object[]& ContextParams, Object[]& CustomParams, wizardResult& retval)
   at EnvDTE._Solution.AddFromTemplate(String FileName, String Destination, String ProjectName, Boolean Exclusive)
   at NuGetClient.Test.Integration.Platform.PlatformContextDetailsBase.CreateAspNetWebSolution(VisualStudioHost host, String solutionDirectory, String projectName, AspNetWebTemplateData templateData) in C:\NuGetClientTests\NuGet.Client.Tests\Platform\PlatformContextDetailsBase.cs:line 94
   at NuGetClient.Test.Integration.Platform.AspNetEmptyPlatformContextDetails.CreateAspNetWebSolution(VisualStudioHost host, String solutionDirectory, String projectName, AspNetWebTemplateData templateData) in C:\NuGetClientTests\NuGet.Client.Tests\Platform\AspNetEmptyPlatformContextDetails.cs:line 36
   at NuGetClient.Test.Integration.Platform.ContextImplementation.CreateAspNetWebSolution(VisualStudioHost host, AspNetWebTemplateData template) in C:\NuGetClientTests\NuGet.Client.Tests\Platform\ContextImplementation.cs:line 86
   at NuGetClient.Test.Integration.Tests.E2E.AbuseLinkTests.AbuseLink() in C:\NuGetClientTests\NuGet.Client.Tests\Tests\E2E\AbuseLinkTests.cs:line 30
Result Message:	System.Runtime.InteropServices.COMException : Cannot create project. The project folder 'C:\school\ApexSolutions\WebApplication\' already exists and contains other files and folders.

**Comment by v-atian** [comment]
cda3f4c46ec2cabf4207cdaad71e93041236ef6d
