### ISSUE TITLE
Can not find tests after adding XunitTestCaseDiscoverer attribute

### ISSUE THREAD

**Issue by v-atian** [v-atian/NuGetClientTests#3]

**Comment by v-atian** [comment]
Run VS as admin

**Comment by v-atian** [comment]
https://github.com/v-atian/NuGetClientTests/commit/0dafcd6ea4882ee7c10dfc8f312a311a0c8fcbc1

**Comment by v-atian** [comment]
NuGet.Client.Tests: Error creating Visual Studio test case for AbuseLink - Wpf.v_4_5_2.VS: System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.

Server stack trace: 
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at NuGetClient.Test.Foundation.TestAttributes.Context.Context.GetUniqueID() in C:\NuGet.Client.Tests\NuGetClientTests\Foundation\TestAttributes\Context\Context.cs:line 157
   at NuGetClient.Test.Foundation.TestAttributes.Context.ContextBaseTestCase.GetUniqueID() in C:\NuGet.Client.Tests\NuGetClientTests\Foundation\TestCommands\Context\ContextBaseTestCase.cs:line 79
   at Xunit.Sdk.TestMethodTestCase.get_UniqueID()
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Xunit.Abstractions.ITestCase.get_UniqueID()
   at Xunit.Runner.VisualStudio.TestAdapter.VsDiscoverySink.CreateVsTestCase(String source, ITestFrameworkDiscoverer discoverer, ITestCase xunitTestCase, Boolean forceUniqueName, LoggerHelper logger, Boolean designMode)

**Comment by v-atian** [comment]
Change the paramater count

**Comment by v-atian** [comment]
https://github.com/v-atian/NuGetClientTests/commit/94c5f65deb59a817074a565910bbe0e4cbc964b0
