### ISSUE TITLE
Exception User-Unhandled System.ArgumentException：'codeLanguage'

### ISSUE THREAD

**Issue by v-atian** [v-atian/NuGetClientTests#33]
at NuGetClient.Test.Integration.Platform.NetCorePlatformContextDetailsBase..ctor(Context context) in C:\NuGetClientTests\NuGet.Client.Tests\Platform\NetCorePlatformContextDetailsBase.cs:line 21
   at NuGetClient.Test.Integration.Platform.NetCoreConsolePlatformContextDetails..ctor(Context context) in C:\NuGetClientTests\NuGet.Client.Tests\Platform\NetCoreConsolePlatformContextDetails.cs:line 18
   at NuGetClient.Test.Integration.Platform.ContextImplementation..ctor(Context context) in C:\NuGetClientTests\NuGet.Client.Tests\Platform\ContextImplementation.cs:line 57
   at NuGetClient.Test.Integration.Platform.ContextExtesions.GetImplementation(Context context) in C:\NuGetClientTests\NuGet.Client.Tests\Platform\ContextExtesions.cs:line 12
   at NuGetClient.Test.Integration.Tests.E2E.AbuseLinkTests.AbuseLink() in C:\NuGetClientTests\NuGet.Client.Tests\Tests\E2E\AbuseLinkTests.cs:line 31

**Comment by v-atian** [comment]
https://github.com/v-atian/NuGetClientTests/commit/94768d1d5a6f9028ac5a01ae673a3eebb5aac9cf
