### ISSUE TITLE
System.TypeInitializationException : The type initializer for 'Microsoft.Test.Apex.VisualStudio.Skus.VisualStudioBaseSku' threw an exception.

### ISSUE THREAD

**Issue by v-atian** [v-atian/NuGetClientTests#4]
Test Name:	AbuseLink - Wpf.v_4_5_2.VS
Test FullName:	NuGet.Client.Tests.Tests.E2E.AbuseLinkTests.AbuseLink
Test Source:	C:\NuGet.Client.Tests\NuGetClientTests\NuGet.Client.Tests\Tests\E2E\AbuseLinkTests.cs : line 18
Test Outcome:	Failed
Test Duration:	0:00:02.294

Result StackTrace:	
at Microsoft.Test.Apex.VisualStudio.Skus.VisualStudioBaseSku..ctor()
   at Microsoft.Test.Apex.VisualStudio.Skus.VisualStudioDefaultSku..ctor()
   at Microsoft.Test.Apex.VisualStudio.Skus.VisualStudioHostSkuFactory.Create(VisualStudioSku sku)
   at Microsoft.Test.Apex.VisualStudio.VisualStudioHostBaseConfiguration.get_TargetHostSku()
   at Microsoft.Test.Apex.VisualStudio.VisualStudioUIHostBase.Microsoft.Test.Apex.Hosts.IExternalUIHostExtended.get_ExecuteablePath()
   at Microsoft.Test.Apex.VisualStudio.VisualStudioUIHostBase.get_ProcessStartInfo()
   at Microsoft.Test.Apex.Hosts.ExternalProcessHost.EnableTargetExecutableProbingPathAssemblyResolution()
   at Microsoft.Test.Apex.Hosts.ExternalProcessHost.OnPreInitialize()
   at Microsoft.Test.Apex.Hosts.Host.RaiseOnPreInitialize()
   at Microsoft.Test.Apex.Providers.DefaultHostProductProvider.TryCreate(HostConfiguration input, Host& product)
   at Microsoft.Test.Apex.Services.FactoryService`2.TryCreate(TInput input, TProduct& product)
   at Microsoft.Test.Apex.Services.FactoryService`2.Create(TInput input)
   at Microsoft.Test.Apex.Operations.CreateHost[THost](HostConfiguration configuration)
   at Microsoft.Test.Apex.Operations.CreateAndStartHost[THost](HostConfiguration configuration)
   at NuGet.Client.Tests.Fixtures.VisualStudioHostFixture.EnsureHost() in C:\NuGet.Client.Tests\NuGetClientTests\NuGet.Client.Tests\Fixtures\VisualStudioHostFixture.cs:line 56
   at NuGet.Client.Tests.Apex.IntegrationNuGetTestClass.EnsureVisualStudioHostForContext() in C:\NuGet.Client.Tests\NuGetClientTests\NuGet.Client.Tests\Apex\IntegrationNuGetTestClass.cs:line 49
   at NuGet.Client.Tests.Tests.E2E.AbuseLinkTests.AbuseLink() in C:\NuGet.Client.Tests\NuGetClientTests\NuGet.Client.Tests\Tests\E2E\AbuseLinkTests.cs:line 20
----- Inner Stack Trace -----
   at Microsoft.Test.Apex.VisualStudio.Skus.VisualStudioBaseSku..cctor()
Result Message:	
System.TypeInitializationException : The type initializer for 'Microsoft.Test.Apex.VisualStudio.Skus.VisualStudioBaseSku' threw an exception.
---- System.MissingMethodException : Method not found: 'Omni.Common.VS.InstallationLocator Omni.Common.VS.InstallationLocator.get_Instance()'.

**Comment by v-atian** [comment]
Apex package issue. Change existed apex reference to latest.

**Comment by v-atian** [comment]
Commit be648c29
