### ISSUE TITLE
Message: [Test Collection Cleanup Failure (NuGet.Client.Tests)]: Microsoft.Test.Apex.Interop.MessageFilterRegistrationException : Failed to CoRegisterMessageFilter of type 'Microsoft.Test.Apex.Interop.RetryMessageFilter', see inner exeption for more details.

### ISSUE THREAD

**Issue by v-atian** [v-atian/NuGetClientTests#5]
------ Run test started ------
[xUnit.net 00:00:00.9869149]   Starting:    NuGet.Client.Tests
[xUnit.net 00:00:37.5241627]     [Test Collection Cleanup Failure (NuGet.Client.Tests)] Microsoft.Test.Apex.Interop.MessageFilterRegistrationException
[xUnit.net 00:00:37.5314498]       Microsoft.Test.Apex.Interop.MessageFilterRegistrationException : Failed to CoRegisterMessageFilter of type 'Microsoft.Test.Apex.Interop.RetryMessageFilter', see inner exeption for more details.
[xUnit.net 00:00:37.5324052]       ---- System.Runtime.InteropServices.COMException : The operation attempted is not supported. (Exception from HRESULT: 0x80004021)
[xUnit.net 00:00:37.5379339]       Stack Trace:
[xUnit.net 00:00:37.5428666]            at Microsoft.Test.Apex.Interop.RetryMessageFilter.Register()
[xUnit.net 00:00:37.5436426]            at Microsoft.Test.Apex.Interop.RetryMessageFilter..ctor(TimeSpan retryTimeout, TimeSpan betweenCallWait)
[xUnit.net 00:00:37.5443250]            at Microsoft.Test.Apex.Interop.RetryMessageFilter..ctor(TimeSpan retryTimeout)
[xUnit.net 00:00:37.5449796]            at Microsoft.Test.Apex.Interop.RetryMessageFilter..ctor()
[xUnit.net 00:00:37.5459349]            at Microsoft.Test.Apex.VisualStudio.Services.ThreadSafeDteAccessorService.GetDteForCurrentThread()
[xUnit.net 00:00:37.5465965]            at Microsoft.Test.Apex.VisualStudio.VisualStudioUIHostBase.get_Dte()
[xUnit.net 00:00:37.5475340]            at Microsoft.Test.Apex.VisualStudio.VisualStudioUIHostBase.ResetVisualStudioStateWithDte()
[xUnit.net 00:00:37.5485327]            at Microsoft.Test.Apex.VisualStudio.VisualStudioUIHostBase.ResetVisualStudioState()
[xUnit.net 00:00:37.5494626]            at Microsoft.Test.Apex.VisualStudio.VisualStudioUIHostBase.EndProcess()
[xUnit.net 00:00:37.5504225]            at Microsoft.Test.Apex.Hosts.ExternalProcessHost.StopCore()
[xUnit.net 00:00:37.5512729]            at Microsoft.Test.Apex.Hosts.Host.Stop()
[xUnit.net 00:00:37.5521945]         C:\NuGet.Client.Tests\NuGetClientTests\NuGet.Client.Tests\Fixtures\VisualStudioHostFixture.cs(61,0): at NuGet.Client.Tests.Fixtures.VisualStudioHostFixture.Dispose()
[xUnit.net 00:00:37.5529202]         C:\NuGet.Client.Tests\NuGetClientTests\NuGet.Client.Tests\Fixtures\ProductContextFixtureFactory.cs(49,0): at NuGet.Client.Tests.Fixtures.ProductContextFixtureFactory.Dispose()
[xUnit.net 00:00:37.5536746]         ----- Inner Stack Trace -----
[xUnit.net 00:00:37.5543534]         
[xUnit.net 00:00:37.5860072]   Finished:    NuGet.Client.Tests
========== Run test finished: 1 run (0:00:39.367694) ==========

**Comment by v-atian** [comment]
Use UI thread help to dispose object instance.

**Comment by v-atian** [comment]
https://github.com/v-atian/NuGetClientTests/commit/f98f35c0d1af3ec366d187d8a118e7006a33a1cf
