### ISSUE TITLE
System.IO.FileLoadException : Could not load file or assembly 'Microsoft.VisualStudio.Threading, Version=15.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

### ISSUE THREAD

**Issue by v-atian** [v-atian/NuGetClientTests#6]
------ Run test started ------
[xUnit.net 00:00:01.1701366]   Starting:    NuGet.Client.Tests
[xUnit.net 00:00:30.4566981]     AbuseLink - Wpf.v_4_5_2.VS [FAIL]
[xUnit.net 00:00:30.4705542]       System.IO.FileLoadException : Could not load file or assembly 'Microsoft.VisualStudio.Threading, Version=15.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
[xUnit.net 00:00:30.4786172]       Stack Trace:
[xUnit.net 00:00:30.4816974]         
[xUnit.net 00:00:30.4830018]         Server stack trace: 
[xUnit.net 00:00:30.4840828]            at Microsoft.Test.Apex.VisualStudio.Services.Remote.VsUIThreadInvokerService.Invoke(RemoteAction action, Object[] methodParameters)
[xUnit.net 00:00:30.4851635]            at Microsoft.Test.Apex.Hosts.Services.UIThreadInvokerHelper.InvokeOn(RemoteInvoker invoker, RemoteAction action, Object[] arguments)
[xUnit.net 00:00:30.4861705]            at Microsoft.Test.Apex.Hosts.Services.UIThreadInvokerHelper.InvokeOn(IRemoteUIThreadInvokerService invoker, RemoteAction action, Object[] arguments)
[xUnit.net 00:00:30.4871677]            at Microsoft.Test.Apex.Hosts.Services.UIThreadInvokerHelper.InvokeOn[T](IRemoteUIThreadInvokerService invoker, Func`1 func)
[xUnit.net 00:00:30.4881270]            at Microsoft.Test.Apex.Hosts.MarshallableApexObject.UIInvoke[T](Func`1 func)
[xUnit.net 00:00:30.4890891]            at Microsoft.Test.Apex.VisualStudio.VisualStudioObjectProviders.System.IServiceProvider.GetService(Type serviceType)
[xUnit.net 00:00:30.4900400]            at Microsoft.Test.Apex.VisualStudio.VisualStudioObjectProviders.GetService(Type serviceType)
[xUnit.net 00:00:30.4943752]            at Microsoft.Test.Apex.VisualStudio.VisualStudioObjectProviders.GetService[TService,TContract]()
[xUnit.net 00:00:30.4953659]            at Microsoft.Test.Apex.VisualStudio.Solution.SolutionService.get_Solution()
[xUnit.net 00:00:30.4963555]            at Microsoft.Test.Apex.VisualStudio.Solution.SolutionService.get_ProjectContainer()
[xUnit.net 00:00:30.4973645]            at Microsoft.Test.Apex.VisualStudio.Solution.SolutionService.CreateProject(ProjectLanguage language, ProjectTemplate template, FrameworkName targetFramework, String projectName)
[xUnit.net 00:00:30.4985878]            at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
[xUnit.net 00:00:30.4995535]            at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
[xUnit.net 00:00:30.5005104]         
[xUnit.net 00:00:30.5014300]         Exception rethrown at [0]: 
[xUnit.net 00:00:30.5023727]            at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
[xUnit.net 00:00:30.5033152]            at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
[xUnit.net 00:00:30.5042962]            at Microsoft.Test.Apex.VisualStudio.Solution.SolutionService.CreateProject(ProjectLanguage language, ProjectTemplate template, FrameworkName targetFramework, String projectName)
[xUnit.net 00:00:30.5053051]         C:\NuGet.Client.Tests\NuGetClientTests\NuGet.Client.Tests\Platform\PlatformContextDetailsBase.cs(63,0): at NuGet.Client.Tests.Platform.PlatformContextDetailsBase.CreateProject(VisualStudioHost host, String projectName, ProjectTemplate projectTemplate, Boolean addToExistingSolution, CodeLanguage codeLanguage)
[xUnit.net 00:00:30.5063247]         C:\NuGet.Client.Tests\NuGetClientTests\NuGet.Client.Tests\Platform\ContextImplementation.cs(72,0): at NuGet.Client.Tests.Platform.ContextImplementation.CreateProject(VisualStudioHost host, ProjectTemplate projectTemplate)
[xUnit.net 00:00:30.5072931]         C:\NuGet.Client.Tests\NuGetClientTests\NuGet.Client.Tests\Tests\E2E\AbuseLinkTests.cs(23,0): at NuGet.Client.Tests.Tests.E2E.AbuseLinkTests.AbuseLink()
[xUnit.net 00:00:33.2204289]   Finished:    NuGet.Client.Tests
========== Run test finished: 1 run (0:00:33.7945797) ==========

**Comment by v-atian** [comment]
need to use higher version of VS2017. Current VS2017 is 15.2

**Comment by v-atian** [comment]
No repro after using latest VS2017. Close it.
