### ISSUE TITLE
Can not get a useable project item

### ISSUE THREAD

**Issue by v-atian** [v-atian/NuGetClientTests#7]
Use to open nuget package manage ui

**Comment by v-atian** [comment]
Server stack trace: 
   at Microsoft.Test.Apex.VisualStudio.Solution.ProjectTestExtension.Find[TProjectItem](SolutionItemFind searchType, String searchText, Int32 maxDepth)
   at Microsoft.Test.Apex.VisualStudio.Solution.ProjectTestExtension.Find(SolutionItemFind searchType, String searchText, Int32 maxDepth)
   at Microsoft.Test.Apex.VisualStudio.Solution.ProjectTestExtension.Find(SolutionItemFind searchType, String searchText)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.Test.Apex.VisualStudio.Solution.ProjectTestExtension.Find(SolutionItemFind searchType, String searchText)
   at NuGet.Client.Tests.Platform.PlatformContextDetailsBase.GetDefaultProjectItem(ProjectTestExtension projectExtension) in C:\NuGetClientTests\NuGet.Client.Tests\Platform\PlatformContextDetailsBase.cs:line 220
   at NuGet.Client.Tests.Platform.ContextImplementation.GetDefaultProjectItem(ProjectTestExtension projectTestExtension) in C:\NuGetClientTests\NuGet.Client.Tests\Platform\ContextImplementation.cs:line 78
   at NuGet.Client.Tests.Tests.E2E.AbuseLinkTests.AbuseLink() in C:\NuGetClientTests\NuGet.Client.Tests\Tests\E2E\AbuseLinkTests.cs:line 24

**Comment by v-atian** [comment]
Microsoft.Test.Apex.VisualStudio.Solution.SolutionException : Cannot find a project item with search type 'FileName' and search text 'Prj_Ix9aG5kOZFn' within project 'Prj_Ix9aG5kOZFn'.

**Comment by v-atian** [comment]
Use another method to open NuGet Package Manage UI
