### ISSUE TITLE
System.NullReferenceException: 'Object reference not set to an instance of an object.'

### ISSUE THREAD

**Issue by v-atian** [v-atian/NuGetClientTests#8]
at Microsoft.Test.Apex.Hosts.MarshallableApexObject.get_Logger()
   at Apex.NuGetClient.PackageManageUI.PackageManageUITestExtension.GetPackageManangeUI(String uniqueName) in C:\NuGet.Client.Test\NuGetClientTests\Apex.NuGetClient\PackageManageUI\PackageManageUITestExtension.cs:line 23
   at NuGet.Client.Tests.Tests.E2E.AbuseLinkTests.AbuseLink() in C:\NuGet.Client.Test\NuGetClientTests\NuGet.Client.Tests\Tests\E2E\AbuseLinkTests.cs:line 32

**Comment by v-atian** [comment]
Apex.NuGetClient.PackageManageUI.PackageManageUITestExtension.LazyPackageManageUITestContract.get returned null.

**Comment by v-atian** [comment]
MEF issue, no value for test contract.

**Comment by v-atian** [comment]
Lazy initialization fail.
   at Microsoft.Test.Apex.Hosts.ExternalUIHost.GetCore[T](Object value)
   at Microsoft.Test.Apex.Hosts.Host.Get[T](Object value)
   at Microsoft.Test.Apex.Hosts.Host.Get[T]()
   at NuGet.Client.Tests.Apex.ApexBaseTestClass.<.ctor>b__7_3() in C:\NuGet.Client.Test\NuGetClientTests\NuGet.Client.Tests\Apex\ApexBaseTestClass.cs:line 37
   at System.Lazy`1.CreateValue()

**Comment by v-atian** [comment]
Fixed in commit f32b13097ef1c65eb529030a59b55bf4b4f97f46
