### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by v-atian** [v-atian/NuGetClientTests#9]
at Apex.NuGetClient.PackageManageUI.PackageManageUITestExtension.get_PackageManangeUITestContract() in C:\NuGet.Client.Test\NuGetClientTests\Apex.NuGetClient\PackageManageUI\PackageManageUITestExtension.cs:line 27
   at Apex.NuGetClient.PackageManageUI.PackageManageUITestExtension.GetPackageManangeUI(String uniqueName) in C:\NuGet.Client.Test\NuGetClientTests\Apex.NuGetClient\PackageManageUI\PackageManageUITestExtension.cs:line 24
   at NuGet.Client.Tests.Tests.E2E.AbuseLinkTests.AbuseLink() in C:\NuGet.Client.Test\NuGetClientTests\NuGet.Client.Tests\Tests\E2E\AbuseLinkTests.cs:line 32

**Comment by v-atian** [comment]
Dup to issue 8
